"""The executive summary must be the generated document, not a fabricated one.

The document is regenerated by `governance/testing/generate_exec_summary.py`
(and by the Compliance Gate when it refreshes evidence), so these tests assert
the *stable* invariants rather than volatile alert counts: it is generator-
stamped, its risk and compliance figures match the registers, and it carries no
fabricated addresses.
"""
import csv
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SUMMARY = REPO_ROOT / "governance" / "executive" / "executive-summary.md"
RISK = REPO_ROOT / "governance" / "risk_register.csv"


def test_summary_is_generator_stamped():
    text = SUMMARY.read_text(encoding="utf-8")
    assert "Auto-generated" in text
    assert "generate_exec_summary.py" in text


def test_summary_risk_counts_match_register():
    text = SUMMARY.read_text(encoding="utf-8")
    risks = Counter(row["risk_level"] for row in csv.DictReader(RISK.open(encoding="utf-8")))
    for level in ("EXTREME", "HIGH", "MEDIUM", "LOW"):
        assert f"{risks.get(level, 0)} {level}" in text


def test_summary_quotes_compliance_score():
    import sys

    sys.path.insert(0, str(REPO_ROOT / "governance" / "testing"))
    import compliance_score  # noqa: PLC0415

    percent = compliance_score.compute()["percent"]
    assert f"{percent}%" in SUMMARY.read_text(encoding="utf-8")


def test_summary_has_no_fabricated_addresses():
    text = SUMMARY.read_text(encoding="utf-8")
    assert "172.26." not in text  # historical fabricated address
