{
 "title": "Process Historian (InfluxDB)",
 "tags": [
  "ot",
  "historian",
  "process"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Intake tank level (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT mean(\"level\") FROM \"process_state\" WHERE (\"asset\" = 'plc_intake') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "query": "SELECT mean(\"chlorine\") FROM \"process_state\" WHERE (\"asset\" = 'plc_treatment') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Control commands and alarms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT mean(\"valve\") FROM \"process_state\" WHERE (\"asset\" = 'plc_intake') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "query": "SELECT mean(\"alarm\") FROM \"process_state\" WHERE (\"asset\" = 'plc_intake') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Historian ingestion (points last cycle)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "SELECT last(\"points\") FROM \"poller_health\" WHERE $timeFilter"
    }
   ]
  }
 ]
}