{
 "title": "OT Security Lab - SOC Overview",
 "tags": [
  "OT",
  "Security",
  "CV"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Industrial Threat Stream (Live)",
   "type": "logs",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"ot_alerts\"}"
    }
   ]
  },
  {
   "title": "Alert Composition",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (alert_type) (count_over_time({job=\"ot_alerts\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Total Security Events",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"ot_alerts\"} [$__range]))"
    }
   ]
  }
 ]
}