#!/bin/sh
# EWS SSH endpoint for the bastion -> EWS engineering hop (conduit C11).
#
# The authorized key is generated by the bastion into the shared `ews_keys`
# volume, so wait for it, install it for the engineer user and serve sshd.
set -eu

until [ -s /keys/authorized_keys ]; do sleep 2; done

mkdir -p /home/engineer/.ssh
cp /keys/authorized_keys /home/engineer/.ssh/authorized_keys
chmod 700 /home/engineer/.ssh
chmod 600 /home/engineer/.ssh/authorized_keys
chown -R engineer:engineer /home/engineer/.ssh

exec /usr/sbin/sshd -D -e
